language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn lint
  - yarn test
  - yarn test:coverage
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: #TO_BE_DEFINED#
  on:
    tags: true
    repo: hmcts/feature-toggle-client
